# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of the photometric measurement uncertainty.
#' 
#' @param M Numeric with length 1. The true GC magnitude
#' @param m0 Numeric with length 1. The offset magnitude
#' @param b0 Numeric with length 1. The uncertainty when M = m0
#' @param b1 Numeric with length 1. Rate at which the uncertainty increases with M
#' @export
err_M_cpp <- function(M, m0 = 25.5, b0 = 0.08836, b1 = 0.645) {
    .Call(`_MATHPOP_err_M_cpp`, M, m0, b0, b1)
}

#' C++ implementation of the completeness fraction.
#' 
#' @param M A numeric vector. The true GC magnitude
#' @param Lim Numeric with length 1. 50% completeness fraction
#' @param a Numeric with length 1. Rate at which the completeness fraction drops with M
#' @export
f_cpp <- function(M, Lim, a = 1.5) {
    .Call(`_MATHPOP_f_cpp`, M, Lim, a)
}

f_cpp_trunc <- function(M, Lim, a = 1.5) {
    .Call(`_MATHPOP_f_cpp_trunc`, M, Lim, a)
}

dnorm_cpp <- function(x, mu, sigma) {
    .Call(`_MATHPOP_dnorm_cpp`, x, mu, sigma)
}

#' C++ implementation to calculate the density function of the noisy GCLF
#'
#' @param M A numeric vector. The observed GC magnitude
#' @param mu Numeric with length 1. True GCLF TO point
#' @param sigma Numeric with length 1. True GCLF dispersion
#' @param m0 Numeric with length 1. The offset magnitude
#' @param b0 Numeric with length 1. The uncertainty when M = m0
#' @param b1 Numeric with length 1. Rate at which the uncertainty increases with M
#' @param n Integer. Number of integration points used to marginalize out the true magnitude. Default to 20.
#' @export
phi_eM_cpp <- function(M, mu, sigma, m0, b0, b1, n = 20L) {
    .Call(`_MATHPOP_phi_eM_cpp`, M, mu, sigma, m0, b0, b1, n)
}

Phi_f_cpp <- function(Lim, mu, sigma, n = 50L, a = 1.5) {
    .Call(`_MATHPOP_Phi_f_cpp`, Lim, mu, sigma, n, a)
}

#' C++ implementation to calculate the proportion of remaining GCs after removal of faint GCs
#' 
#' @param Lim Numeric with length 1. 50% completeness fraction
#' @param mu Numeric with length 1. True GCLF TO point
#' @param sigma Numeric with length 1. True GCLF dispersion
#' @param m0 Numeric with length 1. The offset magnitude
#' @param b0 Numeric with length 1. The uncertainty when M = m0
#' @param b1 Numeric with length 1. Rate at which the uncertainty increases with M
#' @param a Numeric with length 1. Rate at which the completeness fraction drops with M
#' @param n Integer. Number of integration points used to marginalize out the true magnitude. Default to 20.
#' @export
p_eM_cpp <- function(Lim, mu, sigma, m0, b0, b1, a, n = 50L) {
    .Call(`_MATHPOP_p_eM_cpp`, Lim, mu, sigma, m0, b0, b1, a, n)
}

Phi_f_trun_cpp <- function(Lim, mu, sigma, n = 50L, a = 1.5) {
    .Call(`_MATHPOP_Phi_f_trun_cpp`, Lim, mu, sigma, n, a)
}

p_eM_trun_cpp <- function(Lim, mu, sigma, m0, b0, b1, a, TO = 26.3, n = 100L) {
    .Call(`_MATHPOP_p_eM_trun_cpp`, Lim, mu, sigma, m0, b0, b1, a, TO, n)
}

